from agentpluginapi import (
    AgentBinaryDownloadReservation,
    AgentBinaryDownloadTicket,
    DropperExecutionMode,
    ExploiterResult,
    FingerprintData,
    IAgentBinaryRepository,
    IAgentCommandBuilderFactory,
    IAgentEventPublisher,
    IAgentOTPProvider,
    IHTTPAgentBinaryServerRegistrar,
    ILinuxAgentCommandBuilder,
    IPropagationCredentialsRepository,
    ITCPPortSelector,
    IWindowsAgentCommandBuilder,
    LinuxDownloadMethod,
    LinuxDownloadOptions,
    LinuxRunOptions,
    LocalMachineInfo,
    PayloadResult,
    PingScanData,
    PortScanData,
    PortScanDataDict,
    RetrievalError,
    TargetHost,
    TargetHostPorts,
    WindowsDownloadMethod,
    WindowsDownloadOptions,
    WindowsRunOptions,
    WindowsShell,
)
from agentpluginapi.i_linux_agent_command_builder import LinuxPermissionChangeOptions

IAgentEventPublisher.publish
IAgentEventPublisher.event

ITCPPortSelector
ITCPPortSelector.get_free_tcp_port
ITCPPortSelector.min_range
ITCPPortSelector.max_range
ITCPPortSelector.lease_time_sec
ITCPPortSelector.preferred_ports

LocalMachineInfo
LocalMachineInfo.operating_system
LocalMachineInfo.temporary_directory
LocalMachineInfo.get_interface_to_target

PayloadResult
PayloadResult.success
PayloadResult.error_message

PingScanData
PingScanData.response_received
PingScanData.os

PortScanData.protocol
PortScanData.banner
PortScanData.service

PortScanDataDict.closed
PortScanDataDict.get_open_service_ports

TargetHost
TargetHost.ip
TargetHost.operating_system
TargetHost.icmp
TargetHost.ports_status

TargetHostPorts.model_config
TargetHostPorts.tcp_ports
TargetHostPorts.udp_ports
TargetHostPorts.dump_ports

AgentBinaryDownloadReservation
AgentBinaryDownloadReservation.id
AgentBinaryDownloadReservation.operating_system
AgentBinaryDownloadReservation.transform_agent_binary
AgentBinaryDownloadReservation.download_url
AgentBinaryDownloadReservation.download_completed

AgentBinaryDownloadTicket.id
AgentBinaryDownloadTicket.download_url
AgentBinaryDownloadTicket.download_completed

ExploiterResult
ExploiterResult.exploitation_success
ExploiterResult.propagation_success
ExploiterResult.os
ExploiterResult.info
ExploiterResult.error_message

FingerprintData
FingerprintData.os_type
FingerprintData.os_version
FingerprintData.services

RetrievalError

IAgentBinaryRepository
IAgentBinaryRepository.get_agent_binary

IAgentOTPProvider
IAgentOTPProvider.get_otp

IHTTPAgentBinaryServerRegistrar
IHTTPAgentBinaryServerRegistrar.reserve_download
IHTTPAgentBinaryServerRegistrar.operating_system
IHTTPAgentBinaryServerRegistrar.requestor_ip
IHTTPAgentBinaryServerRegistrar.agent_binary_wrapper_template
IHTTPAgentBinaryServerRegistrar.clear_reservation
IHTTPAgentBinaryServerRegistrar.reservation_id

IPropagationCredentialsRepository
IPropagationCredentialsRepository.add_credentials
IPropagationCredentialsRepository.credentials_to_add
IPropagationCredentialsRepository.get_credentials

DropperExecutionMode.NONE
DropperExecutionMode.SCRIPT
DropperExecutionMode.DROPPER

LinuxDownloadMethod.WGET
LinuxDownloadMethod.CURL

LinuxDownloadOptions.agent_destination_path
LinuxDownloadOptions.download_url
LinuxDownloadOptions.download_method

LinuxPermissionChangeOptions.file_path
LinuxPermissionChangeOptions.permissions

LinuxRunOptions.agent_destination_path
LinuxRunOptions.dropper_destination_path
LinuxRunOptions.dropper_execution_mode
LinuxRunOptions.check_dropper_execution

ILinuxAgentCommandBuilder.build_download_command
ILinuxAgentCommandBuilder.build_run_command
ILinuxAgentCommandBuilder.build_permission_change_command
ILinuxAgentCommandBuilder.permission_change_options
ILinuxAgentCommandBuilder.get_command
ILinuxAgentCommandBuilder.reset_command
ILinuxAgentCommandBuilder.download_options
ILinuxAgentCommandBuilder.run_options

WindowsDownloadMethod.WEB_REQUEST
WindowsDownloadMethod.WEB_CLIENT

WindowsShell.CMD
WindowsShell.POWERSHELL

WindowsDownloadOptions.agent_destination_path
WindowsDownloadOptions.download_method
WindowsDownloadOptions.download_url

WindowsRunOptions.agent_destination_path
WindowsRunOptions.dropper_execution_mode
WindowsRunOptions.shell
WindowsRunOptions.dropper_destination_path
WindowsRunOptions.check_dropper_execution

IWindowsAgentCommandBuilder.build_download_command
IWindowsAgentCommandBuilder.build_run_command
IWindowsAgentCommandBuilder.get_command
IWindowsAgentCommandBuilder.reset_command
IWindowsAgentCommandBuilder.download_options
IWindowsAgentCommandBuilder.run_options

IAgentCommandBuilderFactory.create_linux_agent_command_builder
IAgentCommandBuilderFactory.create_windows_agent_command_builder
